### ISSUE TITLE
How to prepare the `grid.txt` file 

### ISSUE THREAD

**Issue by fate1997** [ci-lab-cz/easydock#18]
Thank you for providing such an easy-to-use package.

 I want to ask a stupid question about **how to prepare the `grid.txt` file**. Could someone provide your example `grid.txt` file for me to follow? Thank you so much!

**Comment by DrrDom** [comment]
You my look at this example https://github.com/ci-lab-cz/docking-files/blob/main/CDK6-Q00534/grid.txt in our other repository
